import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { ProjectsGrid } from "@/components/projects-grid";
import { Suspense } from "react";

export default function Home() {
  return (
    <main className="min-h-screen">
      <Suspense fallback={<div className="border-b-2 border-border h-[73px]" />}>
        <Header />
      </Suspense>

      <section className="container mx-auto px-4 py-12">
        <div className="max-w-2xl mb-12">
          <h2 className="text-3xl md:text-4xl font-bold uppercase tracking-tight mb-4">
            Built by Us.
          </h2>
          <p className="text-muted-foreground font-mono text-sm leading-relaxed">
            We made these projects. Yes we did. I mean for now they're just placeholders generated by Google Gemini 3.0 Pro, but hopefully in the future we will have hopefully maybe have maybe hopefully maybe deployed enough projects to actually fill out this site. I need five more words.
          </p>
        </div>

        <Suspense fallback={<div className="text-center py-12 font-mono text-sm text-muted-foreground">Loading...</div>}>
          <ProjectsGrid />
        </Suspense>
      </section>

      <Footer />
    </main>
  );
}
